# frontend/Dockerfile
FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Build para produção
RUN npm run build

# Expor a porta padrão do Next.js
EXPOSE 3000

# Comando para rodar o app em modo produção
CMD ["npm", "start"]