version: "3.9"

services:
  db:
    image: postgres:15
    container_name: scoder_desafio
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: ./backend
    container_name: nest_app
    restart: unless-stopped
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: next_frontend
    restart: unless-stopped
    env_file:
      - .env
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - app

volumes:
  pgdata:
